# Generated by Django 5.1.15 on 2026-07-08 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categorias_servicio',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('email', models.TextField()),
                ('telefono', models.TextField(blank=True, null=True)),
                ('empresa', models.TextField(blank=True, null=True)),
                ('tipo_evento', models.TextField(choices=[('corporativo', 'corporativo'), ('social', 'social'), ('festival', 'festival'), ('otro', 'otro')])),
                ('descripcion', models.TextField()),
                ('fecha_estimada', models.DateField(blank=True, null=True)),
                ('presupuesto_estimado', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(choices=[('nuevo', 'nuevo'), ('en_contacto', 'en_contacto'), ('cotizado', 'cotizado'), ('cerrado', 'cerrado'), ('descartado', 'descartado')], default='nuevo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='EventoTipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evento_tipos',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('imagen_destacada', models.TextField(blank=True, null=True)),
                ('extracto', models.TextField()),
                ('contenido', models.TextField()),
                ('estado', models.TextField(choices=[('borrador', 'borrador'), ('revision', 'revision'), ('publicado', 'publicado')], default='borrador')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('tipo_slug', models.TextField(blank=True, null=True)),
                ('cliente', models.TextField()),
                ('descripcion_corta', models.TextField()),
                ('descripcion_larga', models.TextField()),
                ('imagen_destacada', models.TextField(blank=True, null=True)),
                ('fecha_realizacion', models.DateField()),
                ('lugar', models.TextField()),
                ('asistentes', models.IntegerField(blank=True, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(db_column='tipo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='catalogo.eventotipo')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='FotoEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='catalogo.evento')),
            ],
            options={
                'db_table': 'fotos_evento',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria_slug', models.TextField(blank=True, null=True)),
                ('nombre', models.TextField()),
                ('descripcion_corta', models.TextField()),
                ('descripcion_larga', models.TextField()),
                ('imagen', models.TextField(blank=True, null=True)),
                ('icono_svg', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='catalogo.categoriaservicio')),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='catalogo.post')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='catalogo.tag')),
            ],
            options={
                'db_table': 'post_tags',
                'unique_together': {('post', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', through='catalogo.PostTag', to='catalogo.tag'),
        ),
    ]
