# Generated by Django 5.1.5 on 2026-09-02 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_imagenes_en_bd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionHistorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_nombre', models.TextField(default='Sistema')),
                ('tipo_accion', models.TextField()),
                ('estado_anterior', models.TextField(blank=True, null=True)),
                ('estado_nuevo', models.TextField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(db_column='cotizacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='catalogo.cotizacion')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cotizaciones_historial',
                'ordering': ['-created_at'],
            },
        ),
    ]
